import { notFound } from "next/navigation";
import { Shell } from "@/components/Shell";
import { requireOwner } from "@/lib/auth";
import { addMilestone, addNote, addTask, deleteProject, deleteTask, publishProject, setTaskStatus, unpublishProject, updateProject } from "@/app/actions/owner";
import { AttachmentUploader } from "@/components/AttachmentUploader";

export const dynamic = "force-dynamic";
export const metadata = { title: "Private Project", robots: { index: false, follow: false } };

export default async function OwnerProjectPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const { supabase, user } = await requireOwner();
  const [projectRes, tasksRes, milestonesRes, notesRes, filesRes, pubRes] = await Promise.all([
    supabase.from("projects").select("*").eq("id", id).eq("owner_id", user.id).maybeSingle(),
    supabase.from("tasks").select("*").eq("project_id", id).eq("owner_id", user.id).order("created_at"),
    supabase.from("milestones").select("*").eq("project_id", id).eq("owner_id", user.id).order("sort_order"),
    supabase.from("private_notes").select("id,title,body,updated_at").eq("project_id", id).eq("owner_id", user.id).order("updated_at", { ascending: false }),
    supabase.from("project_files").select("id,original_name,mime_type,byte_size,created_at").eq("project_id", id).eq("owner_id", user.id).order("created_at", { ascending: false }),
    supabase.from("project_publications").select("slug,title,summary,body,technologies,source_url,published,published_at").eq("project_id", id).eq("owner_id", user.id).maybeSingle()
  ]);
  const project = projectRes.data;
  if (!project) notFound();
  const update = updateProject.bind(null, id), remove = deleteProject.bind(null, id), unpublish = unpublishProject.bind(null, id), publication = pubRes.data;
  return <Shell title={`OWNER::${project.name.toUpperCase()}`} privateMode>
    <p><a href="/owner">← PROJECT MONITOR</a></p>
    <div className="grid owner-detail-grid"><section className="panel"><h1>{project.name}</h1><form action={update} className="form-grid"><label>Name<input name="name" defaultValue={project.name} required/></label><label>Codename<input name="codename" defaultValue={project.codename ?? ""}/></label><label>Status<select name="status" defaultValue={project.status}>{["IDEA","PLANNING","ACTIVE","PAUSED","BLOCKED","SHIPPED","ARCHIVED"].map((v)=><option key={v}>{v}</option>)}</select></label><label>Visibility<select name="visibility" defaultValue={project.visibility}>{["PRIVATE","PUBLIC","UNLISTED","ARCHIVED"].map((v)=><option key={v}>{v}</option>)}</select></label><label>Priority<select name="priority" defaultValue={project.priority}>{["LOW","MEDIUM","HIGH","CRITICAL"].map((v)=><option key={v}>{v}</option>)}</select></label><label>Progress mode<select name="progress_mode" defaultValue={project.progress_mode}><option>MANUAL</option><option>DERIVED</option></select></label><label>Progress<input name="progress" type="number" min="0" max="100" defaultValue={project.progress}/></label><label className="wide">Description<textarea name="description" rows={8} defaultValue={project.description}/></label><label>Current milestone<input name="current_milestone" defaultValue={project.current_milestone ?? ""}/></label><label>Next action<input name="next_action" defaultValue={project.next_action ?? ""}/></label><label>Blocker<input name="blocker" defaultValue={project.blocker ?? ""}/></label><label>Technologies<input name="technologies" defaultValue={(project.technologies ?? []).join(", ")}/></label><label>Tags<input name="tags" defaultValue={(project.tags ?? []).join(", ")}/></label><label>Repository URL<input name="repository_url" type="url" defaultValue={project.repository_url ?? ""}/></label><label>Deployment URL<input name="deployment_url" type="url" defaultValue={project.deployment_url ?? ""}/></label><button className="wide">SAVE PROJECT</button></form></section>
    <section className="panel publication-panel"><h2>PUBLISH CONTROL</h2><p className="muted">Publishing copies only these deliberately selected fields into the anonymous-readable projection. Private description/tasks/notes/blockers/files remain separate.</p><form action={publishProject} className="stack-form"><input type="hidden" name="project_id" value={id}/><label>Public slug<input name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" defaultValue={publication?.slug ?? project.name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}/></label><label>Public title<input name="title" required defaultValue={publication?.title ?? project.name}/></label><label>Public summary<textarea name="summary" rows={4} required defaultValue={publication?.summary ?? ""}/></label><label>Public body<textarea name="body" rows={9} defaultValue={publication?.body ?? ""}/></label><label>Public technologies<input name="technologies" defaultValue={(publication?.technologies ?? project.technologies ?? []).join(", ")}/></label><label>Public source URL<input name="source_url" type="url" defaultValue={publication?.source_url ?? project.repository_url ?? ""}/></label><button>{publication?.published ? "UPDATE PUBLISHED RECORD" : "PUBLISH SELECTED FIELDS"}</button></form>{publication?.published ? <form action={unpublish}><button className="danger">UNPUBLISH</button></form> : null}</section></div>
    <div className="grid two"><section className="panel"><h2>TASKS</h2><form action={addTask} className="inline-form"><input type="hidden" name="project_id" value={id}/><input name="title" required placeholder="New task"/><input name="description" placeholder="Description"/><button>ADD</button></form><div className="records">{(tasksRes.data ?? []).map((t)=><div className="record" key={t.id}><div><strong>{t.title}</strong><small>{t.description}</small></div><div className="record-actions"><form action={setTaskStatus.bind(null,t.id,id,t.status === "DONE" ? "TODO" : "DONE")}><button>{t.status === "DONE" ? "REOPEN" : "DONE"}</button></form><form action={deleteTask.bind(null,t.id,id)}><button className="danger">DEL</button></form></div></div>)}</div></section><section className="panel"><h2>MILESTONES</h2><form action={addMilestone} className="stack-form"><input type="hidden" name="project_id" value={id}/><label>Title<input name="title" required/></label><label>Description<textarea name="description" rows={3}/></label><button>ADD MILESTONE</button></form><div className="mini-list">{(milestonesRes.data ?? []).map((m)=><p key={m.id}><strong>{m.title}</strong><span>{m.completed_at ? "DONE" : "OPEN"}</span></p>)}</div></section></div>
    <div className="grid two"><section className="panel"><h2>PRIVATE NOTES</h2><form action={addNote} className="stack-form"><input type="hidden" name="project_id" value={id}/><label>Title<input name="title" required/></label><label>Body<textarea name="description" rows={4}/></label><button>ADD NOTE</button></form>{(notesRes.data ?? []).map((n)=><article className="private-note" key={n.id}><h3>{n.title}</h3><p>{n.body}</p></article>)}</section><section className="panel"><h2>ATTACHMENTS</h2><AttachmentUploader projectId={id}/><div className="mini-list">{(filesRes.data ?? []).map((f)=><p key={f.id}><a href={`/owner/files/${f.id}/download`}>{f.original_name}</a><span>{f.byte_size ? `${Math.ceil(Number(f.byte_size)/1024)} KB` : "—"}</span></p>)}</div></section></div>
    <section className="danger-zone"><h2>DANGER ZONE</h2><form action={remove}><button className="danger">DELETE PROJECT AND CASCADED RECORDS</button></form></section>
  </Shell>;
}
