import Link from "next/link";
import { Shell } from "@/components/Shell";
import { requireOwner } from "@/lib/auth";
import { addIdea, addNote, addTask, createProject, updatePublicStatus } from "@/app/actions/owner";
import { signOutOwner } from "@/app/actions/auth";

export const dynamic = "force-dynamic";
export const metadata = { title: "Owner Workstation", robots: { index: false, follow: false } };

export default async function OwnerPage() {
  const { supabase, user } = await requireOwner();
  const [projectsRes, tasksRes, notesRes, ideasRes, statusRes] = await Promise.all([
    supabase.from("projects").select("id,name,codename,status,visibility,priority,progress,progress_mode,target_date,blocker,updated_at").order("updated_at", { ascending: false }),
    supabase.from("tasks").select("id,project_id,title,status,priority,due_date,updated_at").order("updated_at", { ascending: false }).limit(12),
    supabase.from("private_notes").select("id,project_id,title,updated_at").order("updated_at", { ascending: false }).limit(8),
    supabase.from("ideas").select("id,title,status,category,updated_at").order("updated_at", { ascending: false }).limit(8),
    supabase.from("public_status").select("building,learning,exploring").eq("id", "main").maybeSingle()
  ]);
  const projects = projectsRes.data ?? [];
  const tasks = tasksRes.data ?? [];
  const notes = notesRes.data ?? [];
  const ideas = ideasRes.data ?? [];
  const counts = { projects: projects.length, active: projects.filter((p) => p.status === "ACTIVE").length, blocked: projects.filter((p) => p.status === "BLOCKED" || Boolean(p.blocker)).length, openTasks: tasks.filter((t) => t.status !== "DONE").length };
  return <Shell title="OWNER::PROJECT_MONITOR" privateMode>
    <div className="owner-toolbar"><div><p className="kicker amber-text">VERIFIED OWNER SESSION</p><small>{user.email}</small></div><form action={signOutOwner}><button>UNMOUNT / SIGN OUT</button></form></div>
    <div className="stat-grid"><div><strong>{counts.projects}</strong><span>Projects</span></div><div><strong>{counts.active}</strong><span>Active</span></div><div><strong>{counts.blocked}</strong><span>Blocked</span></div><div><strong>{counts.openTasks}</strong><span>Recent open tasks</span></div></div>
    <section className="panel"><div className="panel-heading"><h2>PROJECT MONITOR</h2><span>PRIVATE TABLE</span></div>{projects.length ? <div className="owner-project-list">{projects.map((p) => <Link key={p.id} href={`/owner/projects/${p.id}`} className="owner-project"><span><strong>{p.name}</strong>{p.codename ? <small>{p.codename}</small> : null}</span><span>{p.status}</span><span>{p.visibility}</span><span>{p.progress}%</span></Link>)}</div> : <p className="muted">No private projects yet.</p>}</section>
    <details className="panel"><summary>NEW PROJECT</summary><form action={createProject} className="form-grid"><label>Name<input name="name" required maxLength={160}/></label><label>Codename<input name="codename" maxLength={100}/></label><label>Status<select name="status" defaultValue="IDEA"><option>IDEA</option><option>PLANNING</option><option>ACTIVE</option><option>PAUSED</option><option>BLOCKED</option><option>SHIPPED</option><option>ARCHIVED</option></select></label><label>Visibility<select name="visibility" defaultValue="PRIVATE"><option>PRIVATE</option><option>PUBLIC</option><option>UNLISTED</option><option>ARCHIVED</option></select></label><label>Priority<select name="priority" defaultValue="MEDIUM"><option>LOW</option><option>MEDIUM</option><option>HIGH</option><option>CRITICAL</option></select></label><label>Progress mode<select name="progress_mode" defaultValue="MANUAL"><option>MANUAL</option><option>DERIVED</option></select></label><label>Progress<input name="progress" type="number" min="0" max="100" defaultValue="0"/></label><label className="wide">Description<textarea name="description" rows={5}/></label><label>Current milestone<input name="current_milestone"/></label><label>Next action<input name="next_action"/></label><label>Blocker<input name="blocker"/></label><label>Technologies<input name="technologies" placeholder="comma,separated"/></label><label>Tags<input name="tags" placeholder="comma,separated"/></label><label>Repository URL<input name="repository_url" type="url"/></label><label>Deployment URL<input name="deployment_url" type="url"/></label><button className="wide" type="submit">CREATE PRIVATE PROJECT</button></form></details>
    <div className="grid two"><section className="panel"><h2>QUICK TASK</h2><form action={addTask} className="stack-form"><label>Project<select name="project_id" defaultValue=""><option value="">General</option>{projects.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Title<input name="title" required/></label><label>Description<textarea name="description" rows={3}/></label><button>ADD TASK</button></form><div className="mini-list">{tasks.map((t) => <p key={t.id}><strong>{t.title}</strong><span>{t.status}</span></p>)}</div></section><section className="panel"><h2>PUBLIC STATUS</h2><form action={updatePublicStatus} className="stack-form"><label>Building<input name="building" defaultValue={statusRes.data?.building ?? ""}/></label><label>Learning<input name="learning" defaultValue={statusRes.data?.learning ?? ""}/></label><label>Exploring<input name="exploring" defaultValue={statusRes.data?.exploring ?? ""}/></label><button>UPDATE PUBLIC STATUS</button></form></section></div>
    <div className="grid two"><section className="panel"><h2>PRIVATE NOTE</h2><form action={addNote} className="stack-form"><label>Project<select name="project_id" defaultValue=""><option value="">General</option>{projects.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Title<input name="title" required/></label><label>Body<textarea name="description" rows={4}/></label><button>STORE NOTE</button></form><div className="mini-list">{notes.map((n) => <p key={n.id}><strong>{n.title}</strong><span>PRIVATE</span></p>)}</div></section><section className="panel"><h2>IDEA BUFFER</h2><form action={addIdea} className="stack-form"><label>Related project<select name="project_id" defaultValue=""><option value="">None</option>{projects.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Title<input name="title" required/></label><label>Description<textarea name="description" rows={4}/></label><button>CAPTURE IDEA</button></form><div className="mini-list">{ideas.map((i) => <p key={i.id}><strong>{i.title}</strong><span>{i.status}</span></p>)}</div></section></div>
  </Shell>;
}
