"use server";
import crypto from "node:crypto";
import { headers } from "next/headers";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireOwner } from "@/lib/auth";
import { csvList, projectSchema, publicationSchema, simpleItemSchema, statusSchema, uploadIntentSchema } from "@/lib/validation";
async function assertSameOrigin(){const h=await headers();const origin=h.get("origin");const host=h.get("x-forwarded-host")||h.get("host");if(origin&&host&&new URL(origin).host!==host)throw new Error("Invalid request origin.");}
const nullable=(value:string)=>value.trim()?value.trim():null;
async function recomputeDerivedProgress(projectId:string){const {supabase,user}=await requireOwner();const {data:project}=await supabase.from("projects").select("progress_mode").eq("id",projectId).eq("owner_id",user.id).maybeSingle();if(project?.progress_mode!=="DERIVED")return;const {data:tasks}=await supabase.from("tasks").select("status").eq("project_id",projectId).eq("owner_id",user.id);const count=tasks?.length??0;const done=tasks?.filter(t=>t.status==="DONE").length??0;await supabase.from("projects").update({progress:count===0?0:Math.round(done/count*100)}).eq("id",projectId).eq("owner_id",user.id);}
export async function createProject(formData:FormData){await assertSameOrigin();const {supabase,user}=await requireOwner();const p=projectSchema.parse(Object.fromEntries(formData));const {data,error}=await supabase.from("projects").insert({owner_id:user.id,name:p.name,codename:nullable(p.codename),description:p.description,status:p.status,visibility:p.visibility,priority:p.priority,progress_mode:p.progress_mode,progress:p.progress_mode==="DERIVED"?0:p.progress,current_milestone:nullable(p.current_milestone),next_action:nullable(p.next_action),blocker:nullable(p.blocker),technologies:csvList(p.technologies),tags:csvList(p.tags),repository_url:nullable(p.repository_url),deployment_url:nullable(p.deployment_url)}).select("id").single();if(error)throw new Error(error.message);redirect(`/owner/projects/${data.id}`);}
export async function updateProject(projectId:string,formData:FormData){await assertSameOrigin();const {supabase,user}=await requireOwner();const p=projectSchema.parse(Object.fromEntries(formData));const {error}=await supabase.from("projects").update({name:p.name,codename:nullable(p.codename),description:p.description,status:p.status,visibility:p.visibility,priority:p.priority,progress_mode:p.progress_mode,progress:p.progress,current_milestone:nullable(p.current_milestone),next_action:nullable(p.next_action),blocker:nullable(p.blocker),technologies:csvList(p.technologies),tags:csvList(p.tags),repository_url:nullable(p.repository_url),deployment_url:nullable(p.deployment_url),updated_at:new Date().toISOString()}).eq("id",projectId).eq("owner_id",user.id);if(error)throw new Error(error.message);if(p.progress_mode==="DERIVED")await recomputeDerivedProgress(projectId);revalidatePath("/owner");revalidatePath(`/owner/projects/${projectId}`);}
export async function deleteProject(projectId:string){await assertSameOrigin();const {supabase,user}=await requireOwner();const {error}=await supabase.from("projects").delete().eq("id",projectId).eq("owner_id",user.id);if(error)throw new Error(error.message);redirect("/owner");}
export async function addTask(formData:FormData){await assertSameOrigin();const {supabase,user}=await requireOwner();const p=simpleItemSchema.parse(Object.fromEntries(formData));const projectId=p.project_id||null;const {error}=await supabase.from("tasks").insert({owner_id:user.id,project_id:projectId,title:p.title,description:p.description});if(error)throw new Error(error.message);if(projectId)await recomputeDerivedProgress(projectId);revalidatePath("/owner");if(projectId)revalidatePath(`/owner/projects/${projectId}`);}
export async function setTaskStatus(taskId:string,projectId:string|null,status:"TODO"|"IN_PROGRESS"|"BLOCKED"|"DONE"){await assertSameOrigin();const {supabase,user}=await requireOwner();const {error}=await supabase.from("tasks").update({status,completed_at:status==="DONE"?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq("id",taskId).eq("owner_id",user.id);if(error)throw new Error(error.message);if(projectId)await recomputeDerivedProgress(projectId);revalidatePath("/owner");if(projectId)revalidatePath(`/owner/projects/${projectId}`);}
export async function deleteTask(taskId:string,projectId:string|null){await assertSameOrigin();const {supabase,user}=await requireOwner();const {error}=await supabase.from("tasks").delete().eq("id",taskId).eq("owner_id",user.id);if(error)throw new Error(error.message);if(projectId)await recomputeDerivedProgress(projectId);revalidatePath("/owner");if(projectId)revalidatePath(`/owner/projects/${projectId}`);}
export async function addMilestone(formData:FormData){await assertSameOrigin();const {supabase,user}=await requireOwner();const p=simpleItemSchema.parse(Object.fromEntries(formData));if(!p.project_id)throw new Error("Project required.");const {error}=await supabase.from("milestones").insert({owner_id:user.id,project_id:p.project_id,title:p.title,description:p.description});if(error)throw new Error(error.message);revalidatePath(`/owner/projects/${p.project_id}`);}
export async function addNote(formData:FormData){await assertSameOrigin();const {supabase,user}=await requireOwner();const p=simpleItemSchema.parse(Object.fromEntries(formData));const {error}=await supabase.from("private_notes").insert({owner_id:user.id,project_id:p.project_id||null,title:p.title,body:p.description});if(error)throw new Error(error.message);revalidatePath("/owner");if(p.project_id)revalidatePath(`/owner/projects/${p.project_id}`);}
export async function addIdea(formData:FormData){await assertSameOrigin();const {supabase,user}=await requireOwner();const p=simpleItemSchema.parse(Object.fromEntries(formData));const {error}=await supabase.from("ideas").insert({owner_id:user.id,related_project_id:p.project_id||null,title:p.title,description:p.description});if(error)throw new Error(error.message);revalidatePath("/owner");}
export async function publishProject(formData:FormData){await assertSameOrigin();const {supabase,user}=await requireOwner();const p=publicationSchema.parse(Object.fromEntries(formData));const {data:project}=await supabase.from("projects").select("id").eq("id",p.project_id).eq("owner_id",user.id).maybeSingle();if(!project)throw new Error("Project not found.");const {error}=await supabase.from("project_publications").upsert({owner_id:user.id,project_id:p.project_id,slug:p.slug,title:p.title,summary:p.summary,body:p.body,technologies:csvList(p.technologies),source_url:nullable(p.source_url),published:true,published_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:"project_id"});if(error)throw new Error(error.message);revalidatePath("/projects");revalidatePath(`/projects/${p.slug}`);revalidatePath(`/owner/projects/${p.project_id}`);}
export async function unpublishProject(projectId:string){await assertSameOrigin();const {supabase,user}=await requireOwner();const {data:row,error}=await supabase.from("project_publications").update({published:false,published_at:null,updated_at:new Date().toISOString()}).eq("project_id",projectId).eq("owner_id",user.id).select("slug").maybeSingle();if(error)throw new Error(error.message);revalidatePath("/projects");if(row?.slug)revalidatePath(`/projects/${row.slug}`);revalidatePath(`/owner/projects/${projectId}`);}
export async function updatePublicStatus(formData:FormData){await assertSameOrigin();const {supabase,user}=await requireOwner();const p=statusSchema.parse(Object.fromEntries(formData));const {error}=await supabase.from("public_status").upsert({id:"main",owner_id:user.id,...p,updated_at:new Date().toISOString()},{onConflict:"id"});if(error)throw new Error(error.message);revalidatePath("/");revalidatePath("/owner");}
function safeFilename(name:string){return name.normalize("NFKD").replace(/[^a-zA-Z0-9._-]+/g,"-").replace(/^-+|-+$/g,"").slice(0,120)||"file";}
export async function createAttachmentUploadIntent(input:{projectId:string;originalName:string;mimeType:string;byteSize:number}){await assertSameOrigin();const p=uploadIntentSchema.parse(input);const {supabase,user}=await requireOwner();const {data:project}=await supabase.from("projects").select("id").eq("id",p.projectId).eq("owner_id",user.id).maybeSingle();if(!project)throw new Error("Project not found.");const path=`${user.id}/${p.projectId}/${crypto.randomUUID()}-${safeFilename(p.originalName)}`;const {data,error}=await supabase.storage.from("private-workstation").createSignedUploadUrl(path);if(error||!data?.token)throw new Error(error?.message||"Could not create upload token.");return {path,token:data.token};}
export async function recordUploadedFile(input:{projectId:string;path:string;originalName:string;mimeType:string;byteSize:number}){await assertSameOrigin();const p=uploadIntentSchema.parse({projectId:input.projectId,originalName:input.originalName,mimeType:input.mimeType,byteSize:input.byteSize});const {supabase,user}=await requireOwner();if(!input.path.startsWith(`${user.id}/${p.projectId}/`))throw new Error("Invalid storage path.");const {error}=await supabase.from("project_files").insert({owner_id:user.id,project_id:p.projectId,storage_path:input.path,original_name:p.originalName,mime_type:p.mimeType,byte_size:p.byteSize});if(error)throw new Error(error.message);revalidatePath(`/owner/projects/${p.projectId}`);}
